# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
# Continuous delivery with JReleaser
# Why not? maven, it creates a nice GitHub release

name: Continuous Deployment to Maven Central Repository
on:
  # Trigger on button click
  workflow_dispatch:
  # Trigger on push on pom.xml changes
  push:
    paths:
      - 'pom.xml'
    branches:
      - 'main'
jobs:
  publish:
    # Slim is one CPU vs 4 for the standard ubuntu-latest
    # Price is at the core by minutes
    runs-on: ubuntu-slim
    steps:

      - name: Git Checkout ${{ github.ref_name }}
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Import Gpg Signing Key
        shell: bash
        run:
          gpg --batch --yes --passphrase "${{ secrets.GPG_SOFTWARE_SIGNING_PASSPHRASE }}" --import <(echo "${{ secrets.GPG_SOFTWARE_SIGNING_KEY }}")

      - name: Publish package
        env:
          # https://central.sonatype.com/usertoken
          JRELEASER_MAVENCENTRAL_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          JRELEASER_MAVENCENTRAL_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          # For snapshot, needed by JReleaser
          JRELEASER_NEXUS2_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          JRELEASER_NEXUS2_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          # Gpg for signing
          JRELEASER_GPG_PASSPHRASE: ${{ secrets.GPG_SOFTWARE_SIGNING_PASSPHRASE }}
          # GitHub Token for release creation
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |

          set -TCEeuo pipefail

          echo "Check config"
          ./mvnw --batch-mode --quiet jreleaser:config > /dev/null

          echo "Stage Artifacts"
          ./mvnw --batch-mode  --quiet -Ppublication

          # Deploy snapshot or release
          echo "Deploy snapshot or release"
          ./mvnw --batch-mode jreleaser:deploy
